
name: Update Anime Information Data JSON
on:
  # schedule:
  #   - cron: '0 0 * * 5'
  push:
    branches:
      - 'feature/connect_aws_website'
    paths:
      - '.github/workflows/update_data.yml'

jobs:
  update_data:
    runs-on: ubuntu-latest
    env:
      MAIN_DIRECTORY: "/home/runner/work/otaku-osasis/otaku-osasis"
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          repository: hanvidlee/otaku-osasis
          ref: 'feature/connect_aws_website'
        
      
      - name: Update anime information data
        run: |
          pwd
          ls -a
          python -u ${{ env.MAIN_DIRECTORY }}/connection/AnimeInformation.py
          git status
